import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    minHeight: 0,
  },
  loadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingTop: 40,
  },
  startState: {
    flex: 1,
    gap: 16,
    paddingBottom: 22,
    paddingTop: 8,
  },
  startTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 14,
  },
  startContent: {
    alignItems: 'center',
    gap: 16,
    paddingBottom: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  startContentCentered: {
    flex: 1,
    justifyContent: 'center',
  },
  startIcon: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  startCopy: {
    alignItems: 'center',
    gap: 6,
  },
  startHistory: {
    borderTopWidth: 1,
    marginTop: 2,
    paddingTop: 10,
  },
  startHistoryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  startHistoryRow: {
    borderBottomWidth: 1,
    gap: 2,
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 7,
  },
  startHistoryTitle: {
    flexShrink: 1,
  },
  timelinePage: {
    flex: 1,
    gap: 14,
    paddingBottom: 16,
    paddingTop: 8,
  },
  timelineTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timelineTopActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  navButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  navButtonSpacer: {
    width: 36,
  },
  metaChip: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  timelineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timelineRailScroll: {
    flex: 1,
    minHeight: 0,
  },
  timelineRailContent: {
    gap: 4,
    paddingBottom: 24,
    paddingTop: 8,
  },
  timelineLineItem: {
    flexDirection: 'row',
    gap: 12,
    minHeight: 78,
  },
  timelineRailColumn: {
    alignItems: 'center',
    position: 'relative',
    width: 22,
  },
  timelineRailSegmentTop: {
    borderRadius: 999,
    height: 6,
    left: 10,
    position: 'absolute',
    top: 0,
    width: 2,
    zIndex: 1,
  },
  timelineRailSegmentBottom: {
    borderRadius: 999,
    bottom: 0,
    left: 10,
    position: 'absolute',
    top: 28,
    width: 2,
    zIndex: 1,
  },
  timelineNodeMarkerFixed: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    top: 6,
    width: 22,
    zIndex: 2,
  },
  timelineLineCopy: {
    borderBottomWidth: 1,
    flex: 1,
    gap: 6,
    paddingBottom: 14,
    paddingTop: 2,
  },
  timelineLineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  timelineLineTitle: {
    flex: 1,
  },
  timelineRowActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  timelineActionButton: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  timelineBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timelineSetCountInline: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },

  timelineSetList: {
    gap: 8,
    marginLeft: 0,
    marginTop: 8,
    paddingBottom: 2,
    paddingLeft: 4,
  },
  timelineSetBlock: {
    gap: 4,
  },
  timelineSetRowContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minHeight: 28,
  },
  timelineSetPressable: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 6,
  },
  timelineSetBranch: {
    borderRadius: 999,
    width: 20,
    height: 2,
  },
  timelineSetDot: {
    borderRadius: 999,
    height: 6,
    width: 6,
  },
  timelineRestRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    paddingLeft: 26,
  },
  timelineSetDeleteButton: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  timelineEmpty: {
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
    minHeight: 240,
    paddingVertical: 32,
  },
  exercisePage: {
    flex: 1,
    gap: 14,
    paddingBottom: 16,
    paddingTop: 10,
  },
  exerciseTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  exerciseTitle: {
    flex: 1,
    marginHorizontal: 12,
    fontFamily: 'Outfit_800ExtraBold',
    fontSize: 22,
    letterSpacing: -0.3,
    lineHeight: 26,
    textAlign: 'center',
  },
  cardArea: {
    flex: 1,
    minHeight: 0,
  },
  cardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  cardHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  cardHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  warmupChip: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  metricsStack: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingBottom: 4,
    paddingTop: 4,
  },
  metricsStackSingle: {
    justifyContent: 'center',
    paddingBottom: 0,
    paddingTop: 0,
  },
  metricsStackPair: {
    gap: 20,
    justifyContent: 'flex-start',
    paddingTop: 12,
  },
  metricsStackTriple: {
    gap: 12,
    justifyContent: 'flex-start',
    paddingTop: 6,
  },
  metricsStackDense: {
    gap: 10,
    justifyContent: 'flex-start',
    paddingBottom: 0,
    paddingTop: 2,
  },
  restBody: {
    alignItems: 'stretch',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 10,
    paddingTop: 6,
  },
  restMainGroup: {
    justifyContent: 'center',
    minHeight: 0,
  },
  restTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timerButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  restSteps: {
    alignItems: 'center',
    gap: 14,
    justifyContent: 'center',
  },
  restStep: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 60,
    minWidth: 64,
    paddingHorizontal: 14,
  },
  presetRow: {
    alignItems: 'center',
    flexDirection: 'row',
    left: 0,
    position: 'absolute',
    right: 0,
    bottom: 12,
    justifyContent: 'space-between',
  },
  presetChip: {
    alignItems: 'center',
    borderRadius: 30,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 66,
    minWidth: 74,
    paddingHorizontal: 16,
  },
  primaryAction: {
    alignItems: 'center',
    borderRadius: 20,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 18,
  },
  secondaryAction: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 16,
  },
  timelineBottomAdd: {
    alignSelf: 'center',
    marginTop: 2,
  },
  inlineError: {
    marginTop: 12,
    textAlign: 'center',
  },
  cardPlaceholder: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  sheetOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.32)',
    flex: 1,
    justifyContent: 'flex-end',
    padding: 12,
  },
  sheetPanel: {
    borderRadius: 30,
    borderWidth: 1,
    gap: 12,
    height: '82%',
    overflow: 'hidden',
    padding: 18,
  },
  sheetBody: {
    flex: 1,
    gap: 12,
    minHeight: 0,
  },
  sheetResultsScroll: {
    flex: 1,
    minHeight: 0,
  },
  sheetBottomDock: {
    gap: 8,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sheetHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  bulkAddHeaderButton: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sheetClose: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  searchShell: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    padding: 0,
  },
  filtersScroll: {
    flexGrow: 0,
  },
  filtersRow: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 8,
  },
  filterChip: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sheetContent: {
    gap: 18,
    paddingBottom: 8,
  },
  catalogSection: {
    gap: 10,
  },
  catalogList: {
    gap: 0,
  },
  catalogRow: {
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  catalogRowPressable: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 56,
    paddingLeft: 14,
    paddingVertical: 10,
  },
  catalogRowCopy: {
    flex: 1,
    gap: 2,
  },
  catalogActionButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
});
