import { StyleSheet } from 'react-native';
import { reedRadii } from '@/design/system';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    minHeight: 0,
  },
  activeWorkoutShell: {
    flex: 1,
    gap: 12,
    minHeight: 0,
    paddingTop: 8,
  },
  activeWorkoutPage: {
    flex: 1,
    minHeight: 0,
  },
  loadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingTop: 40,
  },
  startState: {
    flex: 1,
    gap: 16,
    paddingBottom: 22,
    paddingTop: 8,
  },
  startTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 14,
  },
  startContent: {
    alignItems: 'center',
    gap: 16,
    paddingBottom: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  startContentCentered: {
    flex: 1,
    justifyContent: 'center',
  },
  startIcon: {
    alignItems: 'center',
    borderRadius: reedRadii.md,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  startCopy: {
    alignItems: 'center',
    gap: 6,
  },
  startHistory: {
    borderTopWidth: 1,
    marginTop: 2,
    paddingTop: 10,
  },
  startHistoryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  startHistoryRow: {
    borderBottomWidth: 1,
    gap: 2,
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 7,
  },
  startHistoryTitle: {
    flexShrink: 1,
  },
  timelinePage: {
    flex: 1,
    gap: 16,
    paddingBottom: 0,
    paddingTop: 2,
  },
  navButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  navButtonSpacer: {
    width: 36,
  },
  metaChip: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  timelineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timelineRailScroll: {
    flex: 1,
    minHeight: 0,
  },
  timelineRailContentDocked: {
    gap: 10,
    paddingBottom: 162,
    paddingTop: 8,
  },
  timelineLineItem: {
    flexDirection: 'row',
    gap: 14,
    minHeight: 96,
  },
  timelineRailColumn: {
    alignItems: 'center',
    position: 'relative',
    width: 26,
  },
  timelineRailSegmentTop: {
    borderRadius: reedRadii.pill,
    height: 8,
    left: 12,
    position: 'absolute',
    top: 0,
    width: 2,
    zIndex: 1,
  },
  timelineRailSegmentBottom: {
    borderRadius: reedRadii.pill,
    bottom: 0,
    left: 12,
    position: 'absolute',
    top: 36,
    width: 2,
    zIndex: 1,
  },
  timelineNodeMarkerFixed: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    top: 8,
    width: 26,
    zIndex: 2,
  },
  timelineLineCopy: {
    borderRadius: reedRadii.xl,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    marginBottom: 4,
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 12,
  },
  timelineLineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  timelineLineTitle: {
    flex: 1,
  },
  timelineRowActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  timelineActionButton: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  timelineBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  timelineSetCountInline: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },

  timelineSetList: {
    gap: 10,
    marginLeft: 0,
    marginTop: 10,
    paddingBottom: 2,
    paddingLeft: 6,
  },
  timelineSetBlock: {
    gap: 4,
    overflow: 'hidden',
    position: 'relative',
    borderRadius: reedRadii.sm,
  },
  timelineSetFlash: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: reedRadii.sm,
  },
  timelineSetRowContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 34,
  },
  timelineSetPressable: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  timelineSetBranch: {
    borderRadius: reedRadii.pill,
    width: 24,
    height: 2,
  },
  timelineSetDot: {
    borderRadius: reedRadii.pill,
    height: 8,
    width: 8,
  },
  timelineRestRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingLeft: 34,
  },
  timelineSetDeleteButton: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  timelineEmpty: {
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
    minHeight: 240,
    paddingVertical: 32,
  },
  exercisePage: {
    flex: 1,
    gap: 14,
    paddingBottom: 16,
    paddingTop: 2,
  },
  exerciseTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 32,
  },
  exerciseTitle: {
    fontFamily: 'Outfit_800ExtraBold',
    fontSize: 22,
    letterSpacing: -0.3,
    lineHeight: 26,
    textAlign: 'center',
  },
  statusStripShell: {
    marginBottom: 2,
  },
  statusStripContent: {
    gap: 0,
    paddingBottom: 9,
    paddingHorizontal: 10,
    paddingTop: 9,
  },
  statusStripRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  statusStripNavButton: {
    height: 30,
    width: 30,
  },
  statusStripMetrics: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 0,
  },
  statusStripCenter: {
    alignItems: 'center',
    gap: 4,
    justifyContent: 'center',
    minWidth: 0,
    width: '100%',
  },
  statusStripCenterSingle: {
    gap: 0,
  },
  statusStripPrimaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minWidth: 0,
    width: '100%',
  },
  statusStripSegment: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 5,
    minHeight: 22,
    minWidth: 0,
  },
  statusStripValue: {
    flexShrink: 1,
    fontSize: 14,
    lineHeight: 18,
  },
  statusStripDot: {
    borderRadius: reedRadii.pill,
    height: 3,
    width: 3,
  },
  statusStripMicroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 0,
    justifyContent: 'center',
    maxWidth: '100%',
    minHeight: 18,
  },
  statusStripMicroToken: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 8,
    minWidth: 0,
  },
  statusStripMicroDot: {
    borderRadius: reedRadii.pill,
    height: 3,
    marginHorizontal: 10,
    width: 3,
  },
  statusStripMicroText: {
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 15,
    lineHeight: 18,
  },
  cardArea: {
    flex: 1,
    minHeight: 0,
  },
  cardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  cardHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  cardHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  warmupChip: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  metricsStack: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingBottom: 4,
    paddingTop: 4,
  },
  metricsStackSingle: {
    justifyContent: 'center',
    paddingBottom: 0,
    paddingTop: 0,
  },
  metricsStackPair: {
    gap: 20,
    justifyContent: 'flex-start',
    paddingTop: 12,
  },
  metricsStackTriple: {
    gap: 12,
    justifyContent: 'flex-start',
    paddingTop: 6,
  },
  metricsStackDense: {
    gap: 10,
    justifyContent: 'flex-start',
    paddingBottom: 0,
    paddingTop: 2,
  },
  unilateralSwitchRow: {
    alignSelf: 'center',
    marginBottom: 10,
    width: '48%',
    minWidth: 170,
    maxWidth: 230,
  },
  liveCardShell: {
    borderRadius: reedRadii.xl,
    borderWidth: 1.5,
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    paddingBottom: 18,
    paddingHorizontal: 22,
    paddingTop: 24,
  },
  liveCardBody: {
    alignItems: 'center',
    flex: 1,
    gap: 18,
    justifyContent: 'center',
  },
  liveCardTimerSection: {
    alignItems: 'center',
    gap: 14,
    justifyContent: 'center',
  },
  liveSummaryBody: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    gap: 18,
  },
  liveSummaryMeta: {
    alignItems: 'center',
    gap: 4,
  },
  liveSummaryTitle: {
    textAlign: 'center',
  },
  liveSummaryValue: {
    textAlign: 'center',
  },
  liveSummarySecondary: {
    textAlign: 'center',
  },
  liveSummaryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  liveStartHint: {
    marginBottom: 12,
    textAlign: 'center',
  },
  liveRingButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  liveElapsedTimerShell: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveElapsedTimerRing: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    borderWidth: 12,
    justifyContent: 'center',
  },
  liveElapsedCopy: {
    alignItems: 'center',
    gap: 8,
  },
  liveCardStartState: {
    flex: 1,
    justifyContent: 'center',
  },
  livePrimaryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  livePrimaryButton: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 116,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  liveFinishButton: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 96,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  liveMetricList: {
    alignSelf: 'stretch',
    gap: 10,
  },
  liveMetricRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  liveMetricCopy: {
    flex: 1,
    gap: 2,
  },
  liveMetricActions: {
    flexDirection: 'row',
    gap: 6,
  },
  liveStepButton: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 30,
    minWidth: 44,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  restBody: {
    alignItems: 'stretch',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 10,
    paddingTop: 6,
  },
  restMainGroup: {
    justifyContent: 'center',
    minHeight: 0,
  },
  restTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timerButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  restSteps: {
    alignItems: 'center',
    gap: 14,
    justifyContent: 'center',
  },
  restStep: {
    alignItems: 'center',
    borderRadius: reedRadii.lg,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 60,
    minWidth: 64,
    paddingHorizontal: 14,
  },
  presetRow: {
    alignItems: 'center',
    flexDirection: 'row',
    left: 0,
    position: 'absolute',
    right: 0,
    bottom: 12,
    justifyContent: 'space-between',
  },
  presetChip: {
    alignItems: 'center',
    borderRadius: reedRadii.xl,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 66,
    minWidth: 74,
    paddingHorizontal: 16,
  },
  primaryAction: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 18,
  },
  secondaryAction: {
    alignItems: 'center',
    borderRadius: reedRadii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 16,
  },
  timelineBottomDockWrap: {
    bottom: 10,
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 20,
  },
  timelineBottomDockPanel: {
    borderRadius: reedRadii.xl,
    borderWidth: 1,
    overflow: 'hidden',
  },
  timelineBottomDockContent: {
    gap: 10,
    paddingBottom: 12,
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  timelineBottomPrimaryPressable: {
    borderRadius: reedRadii.sm,
    overflow: 'hidden',
  },
  timelineBottomPrimaryGradient: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  timelineBottomSecondaryButton: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  timelineFinishModalOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineFinishModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  timelineFinishModalBackdropBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  timelineFinishModalBackdropTint: {
    ...StyleSheet.absoluteFillObject,
  },
  timelineFinishModalCard: {
    borderRadius: reedRadii.lg,
    maxWidth: 340,
    width: '84%',
  },
  timelineFinishModalCardContent: {
    gap: 14,
    paddingHorizontal: 18,
    paddingBottom: 18,
    paddingTop: 16,
  },
  timelineFinishModalTitle: {
    textAlign: 'center',
  },
  timelineFinishModalSummary: {
    textAlign: 'center',
  },
  timelineFinishModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  timelineFinishModalButton: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  inlineError: {
    marginTop: 12,
    textAlign: 'center',
  },
  cardPlaceholder: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  sheetOverlay: {
    backgroundColor: 'transparent',
    flex: 1,
    justifyContent: 'flex-end',
    padding: 12,
  },
  sheetPanelFrame: {
    height: '82%',
  },
  sheetPanel: {
    borderRadius: reedRadii.xl,
    flex: 1,
  },
  sheetPanelContent: {
    flex: 1,
    gap: 12,
    minHeight: 0,
    padding: 18,
  },
  sheetBody: {
    flex: 1,
    gap: 12,
    minHeight: 0,
  },
  sheetResultsScroll: {
    flex: 1,
    minHeight: 0,
  },
  sheetBottomDock: {
    gap: 8,
  },
  filterSummaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 22,
    paddingHorizontal: 2,
  },
  filterSummaryLine: {
    flex: 1,
    lineHeight: 16,
  },
  filterSummaryClear: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 22,
    paddingHorizontal: 2,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sheetHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  bulkAddHeaderButton: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sheetClose: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  searchShell: {
    alignItems: 'center',
    borderRadius: reedRadii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    padding: 0,
  },
  searchFilterDivider: {
    alignSelf: 'stretch',
    marginVertical: 10,
    width: 1,
  },
  searchFilterButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 84,
  },
  searchFilterBadge: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    justifyContent: 'center',
    minHeight: 18,
    minWidth: 18,
    paddingHorizontal: 4,
  },
  filterSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
  },
  filterSheetPanelFrame: {
    maxHeight: '82%',
  },
  filterSheetPanel: {
    borderTopLeftRadius: reedRadii.xl,
    borderTopRightRadius: reedRadii.xl,
  },
  filterSheetPanelContent: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 16,
    paddingBottom: 12,
    paddingTop: 14,
  },
  filterSheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterSheetTabs: {
    marginTop: 10,
  },
  filterSheetHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  filterSheetBody: {
    paddingTop: 12,
    paddingBottom: 18,
  },
  filterSectionBlock: {
    gap: 10,
  },
  filterSectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterSectionHeaderCopy: {
    flex: 1,
    gap: 2,
    paddingRight: 10,
  },
  filterSearchShell: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  filterSearchInput: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    padding: 0,
  },
  filterOptionsList: {
    gap: 8,
  },
  filterOptionRow: {
    alignItems: 'center',
    borderRadius: reedRadii.sm,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterOptionLabel: {
    flex: 1,
    paddingRight: 10,
  },
  filterSheetFooter: {
    borderTopWidth: 1,
    gap: 10,
    paddingTop: 12,
  },
  filterSheetFooterSummary: {
    lineHeight: 16,
  },
  filterSheetFooterActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  filterFooterSecondaryButton: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 74,
    paddingHorizontal: 12,
  },
  filterFooterPrimaryButton: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 82,
    paddingHorizontal: 14,
  },
  filtersScroll: {
    flexGrow: 0,
  },
  filtersRow: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 8,
  },
  filterChip: {
    alignItems: 'center',
    borderRadius: reedRadii.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sheetContent: {
    gap: 18,
    paddingBottom: 8,
  },
  catalogSection: {
    gap: 10,
  },
  catalogList: {
    gap: 0,
  },
  catalogRow: {
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  catalogRowPressable: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 56,
    paddingLeft: 14,
    paddingVertical: 10,
  },
  catalogRowCopy: {
    flex: 1,
    gap: 2,
  },
  catalogActionButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
});
